package com.stackroute.studentmanagement.model;

import javax.persistence.*;
import java.time.LocalDate;

/*
Add appropriate annotation/s to map the class and its properties with a Database entity
    - studentId should be unique and generated by the Database
    - table name should be students
 */
@Entity
@Table()
public class Student {

    private Integer studentId;
    private String name;
    private String email;
    private String grade;
    private String phoneNo;
    private LocalDate dateOfAdmission;

    // Define a no argument constructor

    // Define a all argument constructor

    // Define Getter and Setter for all Student fields
}
